name: CI/CD - Pull Request Closed - Pipeline

on:
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}

      - name: Repository Name
        run: echo ${{ github.repository }}

      - name: Get bucket name
        id: get-bucket-name
        run: echo "::set-output name=name::$(echo ${{ github.repository }} | sed 's/loomi\///g')-preview-${{ github.event.pull_request.number }}"

      - name: S3 Search
        id: s3-search-bucket
        run: aws s3 ls s3://${{ steps.get-bucket-name.outputs.name }}

      - name: Delete bucket
        if: success()
        run: |
          aws s3 --recursive rm s3://${{ steps.get-bucket-name.outputs.name }}
          aws s3api delete-bucket --bucket ${{ steps.get-bucket-name.outputs.name }} --region ${{ secrets.AWS_S3_REGION }}